# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

from typing import Any, Callable, List, Optional, Tuple, Union

import math
import numbers
import functools
import collections.abc
from itertools import repeat

import torch
from torch import nn
from torch.nn import functional as F
from torch_utils.misc import assert_shape

#-----------------------------------------------------------------------------------------------------------
# Copied from `timm` to save installation.

def to_2tuple(x):
    if isinstance(x, collections.abc.Iterable) and not isinstance(x, str):
        return tuple(x)
    return tuple(repeat(x, 2))


def _trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    # Values are generated by using a truncated uniform distribution and
    # then using the inverse CDF for the normal distribution.
    # Get upper and lower cdf values
    l = norm_cdf((a - mean) / std)
    u = norm_cdf((b - mean) / std)

    # Uniformly fill tensor with values from [l, u], then translate to
    # [2l-1, 2u-1].
    tensor.uniform_(2 * l - 1, 2 * u - 1)

    # Use inverse cdf transform for normal distribution to get truncated
    # standard normal
    tensor.erfinv_()

    # Transform to proper mean, std
    tensor.mul_(std * math.sqrt(2.))
    tensor.add_(mean)

    # Clamp to ensure it's in the proper range
    tensor.clamp_(min=a, max=b)
    return tensor

def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    with torch.no_grad():
        return _trunc_normal_(tensor, mean, std, a, b)

def drop_path(x, drop_prob: float = 0., training: bool = False, scale_by_keep: bool = True):
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = x.new_empty(shape).bernoulli_(keep_prob)
    if keep_prob > 0.0 and scale_by_keep:
        random_tensor.div_(keep_prob)
    return x * random_tensor

class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """
    def __init__(self, drop_prob: float = 0., scale_by_keep: bool = True):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob
        self.scale_by_keep = scale_by_keep

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training, self.scale_by_keep)

    def extra_repr(self):
        return f'drop_prob={round(self.drop_prob,3):0.3f}'

#-----------------------------------------------------------------------------------------------------------
# Copied from `segmentation_models_pytorch` to save installation.

def patch_first_conv(model, new_in_channels, default_in_channels=3, pretrained=True):
    """Change first convolution layer input channels.
    In case:
        in_channels == 1 or in_channels == 2 -> reuse original weights
        in_channels > 3 -> make random kaiming normal initialization
    """

    # get first conv
    for module in model.modules():
        if isinstance(module, nn.Conv2d) and module.in_channels == default_in_channels:
            break

    weight = module.weight.detach()
    module.in_channels = new_in_channels

    if not pretrained:
        module.weight = nn.parameter.Parameter(
            torch.Tensor(
                module.out_channels,
                new_in_channels // module.groups,
                *module.kernel_size,
            )
        )
        module.reset_parameters()

    elif new_in_channels == 1:
        new_weight = weight.sum(1, keepdim=True)
        module.weight = nn.parameter.Parameter(new_weight)

    else:
        new_weight = torch.Tensor(
            module.out_channels, new_in_channels // module.groups, *module.kernel_size
        )

        for i in range(new_in_channels):
            new_weight[:, i] = weight[:, i % default_in_channels]

        new_weight = new_weight * (default_in_channels / new_in_channels)
        module.weight = nn.parameter.Parameter(new_weight)


def replace_strides_with_dilation(module, dilation_rate):
    """Patch Conv2d modules replacing strides with dilation"""
    for mod in module.modules():
        if isinstance(mod, nn.Conv2d):
            mod.stride = (1, 1)
            mod.dilation = (dilation_rate, dilation_rate)
            kh, kw = mod.kernel_size
            mod.padding = ((kh // 2) * dilation_rate, (kh // 2) * dilation_rate)

            # Kostyl for EfficientNet
            if hasattr(mod, "static_padding"):
                mod.static_padding = nn.Identity()

class EncoderMixin:
    """Add encoder functionality such as:
    - output channels specification of feature tensors (produced by encoder)
    - patching first convolution for arbitrary input channels
    """

    _output_stride = 32

    @property
    def out_channels(self):
        """Return channels dimensions for each tensor of forward output of encoder"""
        return self._out_channels[: self._depth + 1]

    @property
    def output_stride(self):
        return min(self._output_stride, 2**self._depth)

    def set_in_channels(self, in_channels, pretrained=True):
        """Change first convolution channels"""
        if in_channels == 3:
            return

        self._in_channels = in_channels
        if self._out_channels[0] == 3:
            self._out_channels = tuple([in_channels] + list(self._out_channels)[1:])

        patch_first_conv(
            model=self, new_in_channels=in_channels, pretrained=pretrained
        )

    def get_stages(self):
        """Override it in your implementation"""
        raise NotImplementedError

    def make_dilated(self, output_stride):
        if output_stride == 16:
            stage_list = [5]
            dilation_list = [2]

        elif output_stride == 8:
            stage_list = [4, 5]
            dilation_list = [2, 4]

        else:
            raise ValueError(
                "Output stride should be 16 or 8, got {}.".format(output_stride)
            )

        self._output_stride = output_stride

        stages = self.get_stages()
        for stage_indx, dilation_rate in zip(stage_list, dilation_list):
            replace_strides_with_dilation(
                module=stages[stage_indx], dilation_rate=dilation_rate
            )

def preprocess_input(x, mean=None, std=None, input_space="RGB", input_range=None, **kwargs):

    if input_space == "BGR":
        x = x[..., ::-1].copy()

    if input_range is not None:
        if x.max() > 1 and input_range[1] == 1:
            x = x / 255.0
    
    if mean is not None:
        mean = torch.tensor(mean).to(x.device)[None, :, None, None]
        x = x - mean

    if std is not None:
        std = torch.tensor(std).to(x.device)[None, :, None, None]
        x = x / std

    return x

def get_preprocessing_fn():
    params = {'input_space': 'RGB', 'input_range': [0, 1], 'mean': [0.485, 0.456, 0.406], 'std': [0.229, 0.224, 0.225]}
    return functools.partial(preprocess_input, **params)

def conv1x1(in_planes: int, out_planes: int, stride: int = 1) -> nn.Conv2d:
    """1x1 convolution"""
    return nn.Conv2d(in_planes, out_planes, kernel_size=1, stride=stride, bias=False)

def conv3x3(in_planes: int, out_planes: int, stride: int = 1, groups: int = 1, dilation: int = 1) -> nn.Conv2d:
    """3x3 convolution with padding"""
    return nn.Conv2d(
        in_planes,
        out_planes,
        kernel_size=3,
        stride=stride,
        padding=dilation,
        groups=groups,
        bias=False,
        dilation=dilation,
    )


class BasicBlock(nn.Module):
    expansion: int = 1

    def __init__(
        self,
        inplanes: int,
        planes: int,
        stride: int = 1,
        downsample: Optional[nn.Module] = None,
        groups: int = 1,
        base_width: int = 64,
        dilation: int = 1,
        norm_layer: Optional[Callable[..., nn.Module]] = None,
    ) -> None:
        super().__init__()
        if norm_layer is None:
            norm_layer = nn.BatchNorm2d
        if groups != 1 or base_width != 64:
            raise ValueError("BasicBlock only supports groups=1 and base_width=64")
        if dilation > 1:
            raise NotImplementedError("Dilation > 1 not supported in BasicBlock")
        # Both self.conv1 and self.downsample layers downsample the input when stride != 1
        self.conv1 = conv3x3(inplanes, planes, stride)
        self.bn1 = norm_layer(planes)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = conv3x3(planes, planes)
        self.bn2 = norm_layer(planes)
        self.downsample = downsample
        self.stride = stride

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        identity = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)

        if self.downsample is not None:
            identity = self.downsample(x)

        out += identity
        out = self.relu(out)

        return out

class ResNetEncoder(nn.Module, EncoderMixin):
    def __init__(self, 
        block: Callable[..., nn.Module] = BasicBlock,
        groups: int = 1,
        width_per_group: int = 64,
        layers: List[int] = [2, 2, 2, 2],
        norm_layer: Optional[Callable[..., nn.Module]] = nn.Identity,
        out_channels: Tuple[int] = (3, 64, 64, 128, 256, 512), 
    ) -> None:
        super().__init__()
        self._norm_layer = norm_layer

        self.inplanes = 64
        self.dilation = 1
        self.groups = groups
        self.base_width = width_per_group

        self.conv1 = nn.Conv2d(3, self.inplanes, kernel_size=7, stride=2, padding=3, bias=False)
        self.bn1 = norm_layer(self.inplanes)
        self.relu = nn.ReLU(inplace=True)
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)
        self.layer1 = self._make_layer(block, 64, layers[0])
        self.layer2 = self._make_layer(block, 128, layers[1], stride=2)
        self.layer3 = self._make_layer(block, 256, layers[2], stride=2)
        self.layer4 = self._make_layer(block, 512, layers[3], stride=2)

        self._out_channels = out_channels
        self._in_channels = 3
    
    def _make_layer(
        self,
        block: Callable[..., nn.Module],
        planes: int,
        blocks: int,
        stride: int = 1,
    ) -> nn.Sequential:
        norm_layer = self._norm_layer
        downsample = None
        previous_dilation = self.dilation
        if stride != 1 or self.inplanes != planes * block.expansion:
            downsample = nn.Sequential(
                conv1x1(self.inplanes, planes * block.expansion, stride),
                norm_layer(planes * block.expansion),
            )

        layers = []
        layers.append(
            block(
                self.inplanes, planes, stride, downsample, self.groups, self.base_width, previous_dilation, norm_layer, 
            )
        )
        self.inplanes = planes * block.expansion
        for _ in range(1, blocks):
            layers.append(
                block(
                    self.inplanes,
                    planes,
                    groups=self.groups,
                    base_width=self.base_width,
                    dilation=self.dilation,
                    norm_layer=norm_layer, 
                )
            )

        return Sequential(*layers)

    def get_stages(self):
        return [
            nn.Identity(),
            nn.Sequential(self.conv1, self.bn1, self.relu),
            nn.Sequential(self.maxpool, self.layer1),
            self.layer2,
            self.layer3,
            self.layer4,
        ]

    def forward(self, x):
        features = [ x ]

        x = self.relu(self.bn1(self.conv1(x)))
        features.append(x)
        
        x = self.layer1(self.maxpool(x))
        features.append(x)

        x = self.layer2(x)
        features.append(x)

        x = self.layer3(x)
        features.append(x)

        x = self.layer4(x)
        features.append(x)

        return features


class SeparableConv2d(nn.Sequential):
    def __init__(
        self,
        in_channels,
        out_channels,
        kernel_size,
        stride=1,
        padding=0,
        dilation=1,
        bias=True,
    ):
        depthwise_conv = nn.Conv2d(
            in_channels,
            in_channels,
            kernel_size,
            stride=stride,
            padding=padding,
            dilation=dilation,
            groups=in_channels,
            bias=False,
        )
        pointwise_conv = nn.Conv2d(
            in_channels,
            out_channels,
            kernel_size=1,
            bias=bias,
        )
        super().__init__(depthwise_conv, pointwise_conv)


class ASPPConv(nn.Module):
    def __init__(self, in_channels, out_channels, dilation):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(
                in_channels,
                out_channels,
                kernel_size=3,
                padding=dilation,
                dilation=dilation,
                bias=False,
            ),
            nn.ReLU(),
        )
    def forward(self, x: torch.Tensor):
        x = self.net(x)
        return x


class ASPPSeparableConv(nn.Module):
    def __init__(self, in_channels, out_channels, dilation):
        super().__init__()
        self.net = nn.Sequential(
            SeparableConv2d(
                in_channels,
                out_channels,
                kernel_size=3,
                padding=dilation,
                dilation=dilation,
                bias=False,
            ),
            nn.ReLU(),
        )
    def forward(self, x: torch.Tensor):
        x = self.net(x)
        return x


class ASPPPooling(nn.Sequential):
    def __init__(self, in_channels, out_channels):
        super().__init__(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(in_channels, out_channels, kernel_size=1, bias=False),
            nn.ReLU(),
        )

    def forward(self, x):
        size = x.shape[-2:]
        for mod in self:
            x = mod(x)
        return F.interpolate(x, size=size, mode="bilinear", align_corners=False)


class ASPP(nn.Module):
    def __init__(self, in_channels, out_channels, atrous_rates, separable=False):
        super(ASPP, self).__init__()
        modules = []
        modules.append(
            nn.Sequential(
                nn.Conv2d(in_channels, out_channels, 1, bias=False),
                nn.ReLU(),
            )
        )

        rate1, rate2, rate3 = tuple(atrous_rates)
        self.ASPPConvModule = ASPPConv if not separable else ASPPSeparableConv

        modules.append(self.ASPPConvModule(in_channels, out_channels, rate1))
        modules.append(self.ASPPConvModule(in_channels, out_channels, rate2))
        modules.append(self.ASPPConvModule(in_channels, out_channels, rate3))
        modules.append(ASPPPooling(in_channels, out_channels))

        self.convs = nn.ModuleList(modules)

        self.project = nn.Sequential(
            nn.Conv2d(5 * out_channels, out_channels, kernel_size=1, bias=False),
            nn.ReLU(),
        )

    def forward(self, x):
        res = []
        for conv in self.convs:
            res.append(conv(x))
        res = torch.cat(res, dim=1)
        return self.project(res)


class DeepLabV3Decoder(nn.Module):
    def __init__(self, in_channels, out_channels=256, atrous_rates=(12, 24, 36)):
        super().__init__()
        self.aspp = ASPP(in_channels, out_channels, atrous_rates)
        self.project = nn.Sequential(
            nn.Conv2d(out_channels, out_channels, 3, padding=1, bias=False),
            nn.ReLU(),
        )
        self.out_channels = out_channels

    def forward(self, feat):
        feat = self.aspp(feat)
        return self.project(feat)

class DeepLabV3(nn.Module):
    def __init__(self, in_dim: int = 3) -> None:
        super().__init__()
        self.in_dim = in_dim
        self.preprocessing_fn = get_preprocessing_fn() # Expect [0, 1]
        # Build encoder
        self.encoder = ResNetEncoder()
        self.encoder.set_in_channels(in_dim + 2, pretrained=True)
        self.encoder.make_dilated(8)

        # Build decoder
        self.decoder = DeepLabV3Decoder(
            self.encoder._out_channels[-1], 
        )
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        assert_shape(x, [None, self.in_dim, None, None]) # Expect [-1, 1] range
        x = x.detach().clone()
        x[:, :3, :, :] = self.preprocessing_fn(x[:, :3, :, :] / 2 + .5)
        x = torch.cat((
            x, F.affine_grid(torch.eye(2, 3)[None].to(x.device).expand(len(x), -1, -1), x.shape, align_corners=False).permute(0, 3, 1, 2).contiguous()
        ), dim=1)
        feat = self.encoder(x)
        
        # Shallow & Deep Features
        return feat[1], self.decoder(feat[-1]) # (B, 256, H?, W?)

#-----------------------------------------------------------------------------------------------------------
# Custom override modules

class Sequential(nn.Sequential):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
    def forward(self, *input) -> Any:
        for module in self:
            if isinstance(input, torch.Tensor):
                input = module(input)
            elif type(input) == list or type(input) == tuple:
                input = module(*input)
            else:
                raise NotImplementedError(str(type(input)))
        return input

class MyLinear(torch.nn.Module):
    __constants__ = ['in_features', 'out_features']
    in_features: int
    out_features: int
    weight: torch.Tensor

    def __init__(self, in_features: int, out_features: int, bias: bool = True,
                 device=None, dtype=None, lr_multiplier=1) -> None:
        factory_kwargs = {'device': device, 'dtype': dtype}
        super().__init__()
        self.lr_multiplier = lr_multiplier
        self.in_features = in_features
        self.out_features = out_features
        self.weight = torch.nn.Parameter(torch.empty((out_features, in_features), **factory_kwargs))
        if bias:
            self.bias = torch.nn.Parameter(torch.empty(out_features, **factory_kwargs))
        else:
            self.register_parameter('bias', None)
        self.reset_parameters()

    def reset_parameters(self) -> None:
        torch.nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))
        self.weight.data[:] = self.weight.data[:] / (self.lr_multiplier)
        if self.bias is not None:
            fan_in, _ = torch.nn.init._calculate_fan_in_and_fan_out(self.weight)
            bound = 1 / math.sqrt(fan_in) if fan_in > 0 else 0
            torch.nn.init.uniform_(self.bias, -bound / (self.lr_multiplier), bound / (self.lr_multiplier))

    def forward(self, input: torch.Tensor) -> torch.Tensor:
        return F.linear(input, self.weight * self.lr_multiplier, (self.bias * self.lr_multiplier) if self.bias is not None else None)

    def extra_repr(self) -> str:
        return f'in_features={self.in_features}, out_features={self.out_features}, bias={self.bias is not None}'

class MyLayerNorm(torch.nn.Module):
    __constants__ = ['normalized_shape', 'eps', 'elementwise_affine']
    normalized_shape: Tuple[int, ...]
    eps: float
    elementwise_affine: bool

    def __init__(self, normalized_shape, eps: float = 1e-5, elementwise_affine: bool = True,
                 bias: bool = True, device=None, dtype=None, lr_multiplier=1) -> None:
        factory_kwargs = {'device': device, 'dtype': dtype}
        super().__init__()
        if isinstance(normalized_shape, numbers.Integral):
            # mypy error: incompatible types in assignment
            normalized_shape = (normalized_shape,)  # type: ignore[assignment]
        self.normalized_shape = tuple(normalized_shape)  # type: ignore[arg-type]
        self.eps = eps
        self.lr_multiplier = lr_multiplier
        self.elementwise_affine = elementwise_affine
        if self.elementwise_affine:
            self.weight = torch.nn.Parameter(torch.empty(self.normalized_shape, **factory_kwargs))
            if bias:
                self.bias = torch.nn.Parameter(torch.empty(self.normalized_shape, **factory_kwargs))
            else:
                self.register_parameter('bias', None)
        else:
            self.register_parameter('weight', None)
            self.register_parameter('bias', None)

        self.reset_parameters()

    def reset_parameters(self) -> None:
        if self.elementwise_affine:
            torch.nn.init.ones_(self.weight)
            self.weight.data[:] = self.weight.data[:] / self.lr_multiplier
            if self.bias is not None:
                torch.nn.init.zeros_(self.bias)

    def forward(self, input: torch.Tensor) -> torch.Tensor:
        return F.layer_norm(
            input, self.normalized_shape, self.weight * self.lr_multiplier, (self.bias * self.lr_multiplier) if self.bias is not None else None, self.eps)

    def extra_repr(self) -> str:
        return '{normalized_shape}, eps={eps}, ' \
            'elementwise_affine={elementwise_affine}'.format(**self.__dict__)

class MyConv2d(torch.nn.Module):

    __constants__ = ['stride', 'padding', 'dilation', 'groups',
                     'padding_mode', 'output_padding', 'in_channels',
                     'out_channels', 'kernel_size']
    __annotations__ = {'bias': Optional[torch.Tensor]}

    in_channels: int
    _reversed_padding_repeated_twice: List[int]
    out_channels: int
    kernel_size: Tuple[int, ...]
    stride: Tuple[int, ...]
    padding: Union[str, Tuple[int, ...]]
    dilation: Tuple[int, ...]
    transposed: bool
    output_padding: Tuple[int, ...]
    groups: int
    padding_mode: str
    weight: torch.Tensor
    bias: Optional[torch.Tensor]

    def __init__(self,
                 in_channels: int,
                 out_channels: int,
                 kernel_size: Tuple[int, ...],
                 stride: Tuple[int, ...] = 1,
                 padding: Tuple[int, ...] = 0,
                 dilation: Tuple[int, ...] = 1,
                 transposed: bool = False,
                 output_padding: Tuple[int, ...] = (0, 0),
                 groups: int = 1,
                 bias: bool = True,
                 padding_mode: str = 'zeros',
                 lr_multiplier = 1, 
                 device=None,
                 dtype=None, 
                 skip_connect=False) -> None:
        factory_kwargs = {'device': device, 'dtype': dtype}
        super().__init__()
        self.skip_connect = skip_connect

        kernel_size = (kernel_size, kernel_size)
        stride = (stride, stride)
        padding = (padding, padding)
        dilation = (dilation, dilation)

        if groups <= 0:
            raise ValueError('groups must be a positive integer')
        if in_channels % groups != 0:
            raise ValueError('in_channels must be divisible by groups')
        if out_channels % groups != 0:
            raise ValueError('out_channels must be divisible by groups')
        if isinstance(padding, str):
            raise ValueError("Not implemented yet.")

        valid_padding_modes = {'zeros', 'reflect', 'replicate', 'circular'}
        if padding_mode not in valid_padding_modes:
            raise ValueError(f"padding_mode must be one of {valid_padding_modes}, but got padding_mode='{padding_mode}'")
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.stride = stride
        self.padding = padding
        self.dilation = dilation
        self.transposed = transposed
        self.output_padding = output_padding
        self.groups = groups
        self.padding_mode = padding_mode
        self.lr_multiplier = lr_multiplier
        # `_reversed_padding_repeated_twice` is the padding to be passed to
        # `F.pad` if needed (e.g., for non-zero padding types that are
        # implemented as two ops: padding + conv). `F.pad` accepts paddings in
        # reverse order than the dimension.
        self._reversed_padding_repeated_twice = (self.padding[0], self.padding[0], self.padding[0], self.padding[0])

        if transposed:
            self.weight = torch.nn.Parameter(torch.empty(
                (in_channels, out_channels // groups, *kernel_size), **factory_kwargs))
        else:
            self.weight = torch.nn.Parameter(torch.empty(
                (out_channels, in_channels // groups, *kernel_size), **factory_kwargs))
        if bias:
            self.bias = torch.nn.Parameter(torch.empty(out_channels, **factory_kwargs))
        else:
            self.register_parameter('bias', None)

        self.reset_parameters()

    def reset_parameters(self) -> None:
        torch.nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))
        self.weight.data[:] = self.weight.data[:] / self.lr_multiplier
        if self.bias is not None:
            fan_in, _ = torch.nn.init._calculate_fan_in_and_fan_out(self.weight)
            if fan_in != 0:
                bound = 1 / math.sqrt(fan_in)
                torch.nn.init.uniform_(self.bias, -bound / (self.lr_multiplier), bound / (self.lr_multiplier))

    def extra_repr(self):
        s = ('{in_channels}, {out_channels}, kernel_size={kernel_size}'
             ', stride={stride}')
        if self.padding != (0,) * len(self.padding):
            s += ', padding={padding}'
        if self.dilation != (1,) * len(self.dilation):
            s += ', dilation={dilation}'
        if self.output_padding != (0,) * len(self.output_padding):
            s += ', output_padding={output_padding}'
        if self.groups != 1:
            s += ', groups={groups}'
        if self.bias is None:
            s += ', bias=False'
        if self.padding_mode != 'zeros':
            s += ', padding_mode={padding_mode}'
        return s.format(**self.__dict__)

    def __setstate__(self, state):
        super().__setstate__(state)
        if not hasattr(self, 'padding_mode'):
            self.padding_mode = 'zeros'
    
    def _conv_forward(self, input: torch.Tensor, weight: torch.Tensor, bias: Optional[torch.Tensor]):
        if self.padding_mode != 'zeros':
            return F.conv2d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
                            weight, bias, self.stride,
                            (0, 0), self.dilation, self.groups)
        return F.conv2d(input, weight, bias, self.stride,
                        self.padding, self.dilation, self.groups)

    def forward(self, input: torch.Tensor) -> torch.Tensor:
        output = self._conv_forward(input, self.weight * self.lr_multiplier, (self.bias * self.lr_multiplier) if self.bias is not None else None)
        if getattr(self, 'skip_connect', False) and output.shape[1] == input.shape[1]:
            output = output + input
        return output

class DWConv(nn.Module):
    def __init__(self, dim=768, lr_multiplier=1):
        super(DWConv, self).__init__()
        self.dwconv = MyConv2d(dim, dim, 3, 1, 1, bias=True, groups=dim, lr_multiplier=lr_multiplier)

    def forward(self, x, H, W):
        B, N, C = x.shape
        x = x.transpose(1, 2).view(B, C, H, W)
        x = self.dwconv(x)
        x = x.flatten(2).transpose(1, 2)

        return x


class Mlp(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0., lr_multiplier=1):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = MyLinear(in_features, hidden_features, lr_multiplier=lr_multiplier)
        self.dwconv = DWConv(hidden_features, lr_multiplier=lr_multiplier)
        self.act = act_layer()
        self.fc2 = MyLinear(hidden_features, out_features, lr_multiplier=lr_multiplier)
        self.drop = nn.Dropout(drop)
        self.lr_multiplier = lr_multiplier

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, MyLinear):
            trunc_normal_(m.weight, std=.02 / self.lr_multiplier)
            if isinstance(m, MyLinear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, MyLayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0 / self.lr_multiplier)
        elif isinstance(m, MyConv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out) / self.lr_multiplier)
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, x, H, W):
        x = self.fc1(x)
        x = self.dwconv(x, H, W)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x

class Attention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, qk_scale=None, attn_drop=0., proj_drop=0., sr_ratio=1, lr_multiplier=1.):
        super().__init__()
        assert dim % num_heads == 0, f"dim {dim} should be divided by num_heads {num_heads}."

        self.dim = dim
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim ** -0.5
        self.lr_multiplier = lr_multiplier

        self.q = MyLinear(dim, dim, bias=qkv_bias, lr_multiplier=lr_multiplier)
        self.kv = MyLinear(dim, dim * 2, bias=qkv_bias, lr_multiplier=lr_multiplier)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = MyLinear(dim, dim, lr_multiplier=lr_multiplier)
        self.proj_drop = nn.Dropout(proj_drop)

        self.sr_ratio = sr_ratio
        if sr_ratio > 1:
            self.sr = MyConv2d(dim, dim, kernel_size=sr_ratio, stride=sr_ratio, lr_multiplier=lr_multiplier)
            self.norm = MyLayerNorm(dim, lr_multiplier=lr_multiplier)

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, MyLinear):
            trunc_normal_(m.weight, std=.02 / self.lr_multiplier)
            if isinstance(m, MyLinear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, MyLayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0 / self.lr_multiplier)
        elif isinstance(m, MyConv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out) / self.lr_multiplier)
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, x, H, W):
        B, N, C = x.shape
        q = self.q(x).reshape(B, N, self.num_heads, C // self.num_heads).permute(0, 2, 1, 3)

        if self.sr_ratio > 1:
            x_ = x.permute(0, 2, 1).reshape(B, C, H, W)
            x_ = self.sr(x_).reshape(B, C, -1).permute(0, 2, 1)
            x_ = self.norm(x_)
            kv = self.kv(x_).reshape(B, -1, 2, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        else:
            kv = self.kv(x).reshape(B, -1, 2, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        k, v = kv[0], kv[1]

        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)

        x = (attn @ v).transpose(1, 2).reshape(B, N, C)
        x = self.proj(x)
        x = self.proj_drop(x)

        return x

class OverlapPatchEmbed(nn.Module):
    """ Image to Patch Embedding
    """

    def __init__(self, img_size=224, patch_size=3, stride=4, in_chans=3, embed_dim=768, dropout_p=0.):
        super().__init__()
        img_size = to_2tuple(img_size)
        patch_size = to_2tuple(patch_size)

        self.img_size = img_size
        self.patch_size = patch_size
        self.H, self.W = img_size[0] // patch_size[0], img_size[1] // patch_size[1]
        self.num_patches = self.H * self.W
        self.dropout_p = dropout_p
        self.proj = nn.Conv2d(in_chans, embed_dim, kernel_size=patch_size, stride=stride,
                              padding=(patch_size[0] // 2, patch_size[1] // 2))
        self.norm = nn.LayerNorm(embed_dim)
        self.dropout = nn.Dropout1d(dropout_p)
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, x):
        x = self.proj(x)
        _, _, H, W = x.shape
        x = x.flatten(2).transpose(1, 2)
        x = self.norm(x)
        x = getattr(self, "dropout", lambda x: x)(x)

        return x, H, W

class TransformerBlock(nn.Module):

    def __init__(self, dim, num_heads, mlp_ratio=4., qkv_bias=True, qk_scale=None, drop=0., attn_drop=0., drop_path=0., act_layer=nn.GELU, norm_layer=MyLayerNorm, sr_ratio=1, return_H_W=False, reshape_H_W=False, lr_multiplier=1.):
        super().__init__()
        self.return_H_W = return_H_W
        self.reshape_H_W = reshape_H_W
        self.norm1 = norm_layer(dim, lr_multiplier=lr_multiplier)
        self.attn = Attention(
            dim,
            num_heads=num_heads, qkv_bias=qkv_bias, qk_scale=qk_scale,
            attn_drop=attn_drop, proj_drop=drop, sr_ratio=sr_ratio, lr_multiplier=lr_multiplier)
        # NOTE: drop path for stochastic depth, we shall see if this is better than dropout here
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.norm2 = norm_layer(dim, lr_multiplier=lr_multiplier)
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = Mlp(in_features=dim, hidden_features=mlp_hidden_dim, act_layer=act_layer, drop=drop, lr_multiplier=lr_multiplier)
        self.lr_multiplier = lr_multiplier

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, MyLinear):
            trunc_normal_(m.weight, std=.02 / self.lr_multiplier)
            if isinstance(m, MyLinear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, MyLayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0 / self.lr_multiplier)
        elif isinstance(m, MyConv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out) / self.lr_multiplier)
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, x, H, W):
        # print("Before:", x.shape, H, W)
        x = x + self.drop_path(self.attn(self.norm1(x), H, W))
        x = x + self.drop_path(self.mlp(self.norm2(x), H, W))
        # print("After:", x.shape, H, W)

        if self.reshape_H_W:
            x = x.reshape(x.shape[0], H, W, x.shape[-1]).permute(0, 3, 1, 2).contiguous()

        if not self.return_H_W:
            return x
        else:
            return x, H, W


class LowResFeatureEncoder(nn.Module):
    def __init__(self, img_resolution: int, lr_multiplier: float = 1., dropout_p=0.) -> None:
        super().__init__()
        self.net = Sequential(
            OverlapPatchEmbed(img_size=img_resolution // 8, stride=2, in_chans=256, embed_dim=1024, dropout_p=dropout_p), 
            TransformerBlock(dim=1024, num_heads=4, mlp_ratio=2, sr_ratio=1, return_H_W=True, lr_multiplier=lr_multiplier), 
            TransformerBlock(dim=1024, num_heads=4, mlp_ratio=2, sr_ratio=1, reshape_H_W=True, lr_multiplier=lr_multiplier), 
            nn.PixelShuffle(upscale_factor=2), 
            nn.UpsamplingBilinear2d(scale_factor=2), 
            nn.Conv2d(256, 128, kernel_size=3, stride=1, padding=1), 
            nn.LeakyReLU(), 
        )
        self.project = nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1)
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.net(x)
        return self.project(x)

class HighResFeatureEncoder(nn.Module):
    def __init__(self, dropout_p=0.) -> None:
        super().__init__()
        self.in_layer = nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1)
        self.dropout = nn.Dropout2d(dropout_p)
        self.layer1 = nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1)
        self.layer2 = nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1)
        self.layer3 = nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1)
        self.layer4 = nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1)
        self.out_layer = nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1)
        self.activation = nn.LeakyReLU()
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = getattr(self, "dropout", lambda x: x)(self.activation(self.in_layer(x)))
        x = self.activation(self.layer1(x))
        x = self.activation(self.layer2(x))
        x = self.activation(self.layer3(x))
        x = self.activation(self.layer4(x))
        x = self.out_layer(x)
        return x

class FeatureDecoder(nn.Module):
    def __init__(self, img_resolution: int, lr_multiplier: float = 1., out_dim: int = 96) -> None:
        super().__init__()
        self.in_layer = Sequential(
            nn.Conv2d(256, 256, kernel_size=3, stride=1, padding=1), 
            OverlapPatchEmbed(img_size=img_resolution // 4, stride=2, in_chans=256, embed_dim=1024), 
            TransformerBlock(dim=1024, num_heads=2, mlp_ratio=2, sr_ratio=2, reshape_H_W=True, lr_multiplier=lr_multiplier), 
            nn.PixelShuffle(2), 
        )
        self.layer_1 = nn.Conv2d(256, 256, kernel_size=3, stride=1, padding=1)
        self.layer_2 = nn.Conv2d(256, 128, kernel_size=3, stride=1, padding=1)
        self.layer_3 = nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1)
        self.layer_4 = nn.Conv2d(128, out_dim, kernel_size=3, stride=1, padding=1)
        self.activation_layer = nn.LeakyReLU()
        self.upsample_layer = nn.UpsamplingBilinear2d(scale_factor=2)
        self.out_layer = nn.Conv2d(out_dim, out_dim, kernel_size=3, stride=1, padding=1)
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.in_layer(x)
        x = self.activation_layer(self.layer_1(x))
        x = self.upsample_layer(x)
        x = self.activation_layer(self.layer_2(x))
        x = self.activation_layer(self.layer_3(x))
        x = self.activation_layer(self.layer_4(x))
        return self.out_layer(x)

class LP3DBackbone(nn.Module):
    def __init__(self, 
        img_resolution: int = 512, 
        feat_dim: int = 96, 
    ) -> None:
        super().__init__()
        self.img_resolution = img_resolution
        self.feat_dim = feat_dim
        self.deep_lab_v3 = DeepLabV3()
        self.low_feat_encoder = LowResFeatureEncoder(img_resolution, lr_multiplier=0.5, dropout_p=0.)
        self.high_feat_encoder = HighResFeatureEncoder(dropout_p=0.)
        self.feat_decoder = FeatureDecoder(img_resolution, lr_multiplier=0.5, out_dim=feat_dim * 3)
    
    def forward(self, image: torch.Tensor) -> torch.Tensor:
        high_res_feat, low_res_feat = self.deep_lab_v3(image)
        low_res_feat = self.low_feat_encoder(low_res_feat)
        high_res_feat = self.high_feat_encoder(high_res_feat)
        planes = self.feat_decoder(torch.cat((low_res_feat, high_res_feat), dim=1))
        assert_shape(planes, [None, self.feat_dim * 3, None, None])
        planes = planes.view(len(planes), 3, self.feat_dim, planes.shape[-2], planes.shape[-1])
        return planes